spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/coupon?serverTimezone=Asia/Seoul
    username: myuser
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      isolation-level: read_committed
    listener:
      ack-mode: record
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1  # all
